export const test: string
export const flag: string
export const flex: string
export const title: string
export const image: string
export const name: string
export const item: string
export const itemIcon: string
export const itemText: string
export const value: string
export const key: string
export const button: string
