declare const require: any
declare const module: any
declare let global: any
declare let test: any
declare let expect: any
declare let shallow: any
declare let render: any
declare let mount: any
declare var describe: any
declare var it: any
